---
title: "01 - Lineare Regression"
output: 
  learnr::tutorial:
    progressive: true
    theme: lumen
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
#Hallo 
library(learnr)
library(gradethis)
knitr::opts_chunk$set(echo = FALSE)
tutorial_options(
  exercise.reveal_solution = FALSE,
  exercise.checker = gradethis::gradethis_exercise_checker
)
```

## Grundlagen von R

### Aufgabe 1

Berechne mit R den Mittelwert der Zahlen 1, 3 und 10.

```{r twotwo, exercise=TRUE}

```

```{r twotwo-solution}
mean(c(1,3,10))
```

```{r twotwo-check}
grade_this({
  if (identical(.result, .solution)) {
    pass(praise = TRUE)
  } else {
    fail(message = "Leider falsch.")
  }
})
```


## Lineare Regression

### Aufgabe 1

Wofür steht der Parameter $\beta_0$ bei einer Regression? (Schreibe die Lösung zwischen die Anführungszeichen)

```{r three, exercise=TRUE, exercise.cap = "Text", exercise.lines = 1}
""
```

```{r three-solution}
"y-Achsenabschnitt"
```

```{r three-check}
grade_this({
  if (.result %in% c("y-Achsenabschnitt", "Intercept", "y achsenabschnitt")) {
      pass(praise = TRUE)
} else {
  fail(message = "Leider falsch.")
}
})
```


### Aufgabe 2

```{r quiz}
quiz(
  question("Wofür steht der Parameter $\\beta_0$ in einer linearen Regression?",
    answer("Prädiktor", message = "Der Prädiktor wird mit x abgekürzt."),
    answer("Outcome", message = "Das Outcome wird mit y abgekürzt."),
    answer("y-Achsenabschnitt", correct = TRUE),
    answer("Steigung", message = "$\\beta_1$ ist die Steigung."),
    allow_retry = TRUE,
    random_answer_order = TRUE,
    incorrect = "Leider falsch.",
    correct = random_praise()
  ),
  question("Which of the R packages listed below are used to create plots?",
    answer("lattice", correct = TRUE),
    answer("tools"),
    answer("stats"),
    answer("grid", correct = TRUE)
  )
)
```


