
# 1 ethische Probleme KI 

## 1 PotAs
Es wird aus historischen Daten das Potential bzw. Risiko vorhergesagt und auf Grundlage dieser Analyse die Unterstützung /Förderung für die einzelnen Sportarten/Sportler verteilt. Grundlage ist das Attributsystem.  A1 (langfristiger Erfolg), A2 (Vorolympishce Erfahrung), A4 (Olympische Erfolge) werden über ein Punktesystem bestimmt. A5 (Perspektive Top 3) und A6 (Perspektive Top 8) werden mit Hilfe eines Elo-Rankings und einer Monte-Carlo-Simulation unter Berücksichtigung des Alters bestimmt.

https://www.potas.de/DE/Fakten-ueber-PotAS/fakten-ueber-potas_uebersicht_node.html <br>


## Review Studie
Insbesondere Kapitel 3.3 und 4.1 der Studie behandelt das Thema Fairness und betont eine mögliche Diskriminierung durch unterrepräsentierte Gruppen. Ich habe hier aber von keinem explizieten Fall gelesen (wie es in dem Kurzartikel dargestellt wird).

Kurzartikel 
https://english.news.cn/20260607/3a9a79dfec824c4fbfe417498c9dd08f/c.html 
Studie 
https://www.sciencedirect.com/science/article/pii/S2095254625000250

## Nutzung von KI bei der Dopingbekämpfung 
fehlende Transparenz/bzw. ist es auch noch garnicht umgesetzt worden von der WADA/NADA. Es gibt nur einen Verweis aus der Arbeitgruppe auf ein Tool aus Großbritannien (dieses Tool wird mit Diskriminierungsvorwürfen kritisiert).

https://www.deutschlandfunk.de/ki-anti-doping-fahndung-100.html

## Ethik Leitlinien Landessportbund NRW

https://www.vibss.de/fileadmin/co_theme/Default/Media/Vereinsmanagement/Digitalisierung/KI/Ethik-Leitlinie_Kuenstliche_Intelligenz_KI.pdf

## Anti Diskrimierungsgesetz 2023 eingeführt("KI Act")
Hier steht drin, dass Maßnahmen zur Minimierung von Diskriminierung durch KI-Algorithmen ergriffen werden müssen. Wie gut das bisher umgesetzt wird ist natürlich fraglich...
Das könnte natürlich erklären warum es nicht so viele Fälle im Sport gibt. Ein weiterer Punkt ist, dass im Sport KI noch nicht so integriert ist wie in anderen Branchen und daher aus deren Fehlern gelernt wird/wurde.

https://artificialintelligenceact.eu/de/



# Weitere Infos 
## Formen von Diskrminierung durch KI 
**Unmittelbare Diskriminierung**: Menschen werden direkt aufgrund geschützter Merkmale wie Herkunft, Geschlecht oder Religion benachteiligt. <br>
**Mittelbare Diskriminierung**: Auf den ersten Blick neutrale Kriterien führen indirekt zu Benachteiligung – etwa durch die Bewertung von Teilzeitbeschäftigung, die häufiger Frauen betrifft.<br>
**Statistische Diskriminierung**: KI nutzt sogenannte Stellvertreter-Variablen wie den Wohnort, die mit sensiblen Merkmalen korrelieren – und verstärkt so ungewollt bestehende Vorurteile.<br>
**Präferenzbasierte Diskriminierung**: Wenn ein System mit Daten trainiert wird, die bestehende gesellschaftliche Vorurteile abbilden – oder sogar die impliziten Vorannahmen der Entwickler widerspiegeln.
